---
title: "plotly"
author: "Louis Sharp"
date: "10/28/2021"
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("rest_inspec")

rest_inspec = 
  rest_inspec %>% 
  drop_na(grade_date) %>% 
  mutate(boro = str_to_title(boro)) %>% 
  filter(boro == "Bronx",
         grade %in% c("A", "B", "C"),
         critical_flag == "Critical") %>% 
  separate(grade_date, into = c("year", "month", "day"), sep = "\\-")

rest_inspec %>% 
  group_by(year, month) %>%
  summarize(n = n()) %>% 
  plot_ly(x = ~year, y = ~n, color = ~month, type = "scatter", mode = "line", colors = "viridis")

rest_inspec %>% 
  group_by(year, month) %>%
  summarize(n = n()) %>% 
  plot_ly(y = ~n, color = ~month, type = "box", colors = "viridis")

rest_inspec %>% 
  group_by(cuisine_description) %>%
  summarize(n = n()) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  plot_ly(x = ~cuisine_description, y = ~n, 
          color = ~cuisine_description, type = "bar", colors = "viridis")
```

```{r}
nynoaa = read_csv("data/nynoaadat.csv") %>% 
  mutate(date = as.character(date),
         tmax = tmax / 10,
         tmin = tmin / 10) %>% 
  filter(id == "USW00094728",
         grepl("20[0-20]", date))

nynoaa %>%
  plot_ly(x = ~date, y = ~tmax, color = ~tmin, type = "scatter", mode = "markers")

nynoaa %>% 
  mutate(date = gsub("\\-.*","",date)) %>% 
  group_by(tmax) %>% 
  summarize(n = n(), date) %>% 
  arrange(desc(tmax)) %>% 
  plot_ly(x = ~tmax, y = ~n, color = ~date, type = "bar", colors = "viridis")

nynoaa %>% 
  mutate(date = gsub("\\-.*","",date)) %>% 
  group_by(tmax) %>% 
  summarize(n = n(), date) %>% 
  arrange(desc(tmax)) %>% 
  plot_ly(x = ~date, y = ~tmax, color = ~n, type = "box", colors = "viridis")
```

